[main]
# Path to your active desktop background
background=/home/anish/Pictures/Library/Vista_Ultimate_2.png

modules=userinfo-module

# Load your system widget components
gtk-theme=Adwaita

# Custom CSS file location
style=/home/anish/.config/gtklock/style.css

# Time & Date layout formatting (12-hour format with AM/PM)
time-format=%I:%M %p
date-format=%A, %B %d, %Y

# QoL adjustments
follow-focus=true
idle-hide=true

[userinfo]
# This centers the username and graphic directly in line with your CSS rules
position=center


